// Shared curated options for instruments and genres
// Used in: /dashboard/profile, /onboarding/profile, MemberFilters

export const INSTRUMENT_OPTIONS = [
  "Vocals / Singing",
  "Guitar",
  "Bass",
  "Piano / Keys",
  "Drums",
  "Cajón",
  "Ukulele",
  "Baritone Ukulele",
  "Mandolin",
  "Banjo",
  "Violin / Fiddle",
  "Cello",
  "Accordion",
  "Lyricist",
  "Poet / Spoken Word",
  "Producer",
  "Audio Engineer",
  "Venue Owner",
];

export const GENRE_OPTIONS = [
  "Folk",
  "Americana",
  "Country",
  "Rock",
  "Indie",
  "Pop",
  "Singer-Songwriter",
  "Blues",
  "Jazz",
  "R&B / Soul",
  "Hip-Hop",
  "Electronic",
  "Classical",
  "Bluegrass",
  "Alternative",
  "Punk",
];

export const SPECIALTY_OPTIONS = [
  "Vocals",
  "Guitar",
  "Piano/Keys",
  "Bass",
  "Drums",
  "Songwriting",
  "Production",
  "Mixing/Mastering",
  "Session Work",
  "Live Performance",
  "Music Theory",
  "Arrangement",
  "Lyrics",
  "Melody",
  "Beat Making",
  "Sound Design",
];
